GET https://fullstack-phonebook-ogia.onrender.com/api/persons

###
POST https://fullstack-phonebook-ogia.onrender.com/api/persons
Content-Type: application/json

{
	"name": "Test Person",
	"number": "999"
}

###
GET https://fullstack-phonebook-ogia.onrender.com/api/persons